### ISSUE TITLE
Question about downloading shape files.

### ISSUE THREAD

**Issue by jwhyb** [granularag/USBuildingFootprints#2]
Newbie question: If I just wanted to simply download one of the county shape files from your bucket and use it in QGIS, how would I go about doing it? I am familiar with python, however I am not at all familiar with fiona or AWS (Nor do I have an AWS account).

**Comment by onimonipea** [comment]
I also can't get this to run. Can we have a more detailed explanation of how to run this code?

**Comment by chipfranzen** [comment]
Hi, you will need valid AWS credentials. I recommend installing `aws-cli` and using that to interact with the bucket.

https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html

If you run `aws configure` you will be prompted to enter your AWS credentials and a credentials file will be generated. AWS SDKs should then just work. I've used the Python SDK, `boto3` in the example script.
